package celtech.roboxbase.postprocessor.nouveau;

/**
 *
 * @author Ian
 */
public enum PostProcessorFeature
{
    FIRST_LAYER_OVERTRAVEL_CLOSE,
    REMOVE_ALL_UNRETRACTS,
    OPEN_NOZZLE_FULLY_AT_START,
    REPLENISH_BEFORE_OPEN,
    OPEN_AND_CLOSE_NOZZLES,
    INSERT_CAMERA_CONTROL_POINTS,
    RETRACT_AT_TOOLCHANGE,
    MOVE_PERIMETERS_TO_FRONT,
    MOVE_SUPPORT_AFTER_MODEL
}
